@startuml classes overview
    session_handle <|-- session
    session o-- session_impl
    session o-- io_context
    session o-- thread

    session_impl *-- alert_manager
    session_impl *-- handler_storage
    session_impl "1" o-- "0..*" block_info
    session_impl *-- peer_class_pool
    session_impl "1" o-- "0..*" peer_connection
    session_impl "1" o-- "0..*" endpoint: m_dht_nodes
    session_impl *-- dht_state
    session_impl *-- dht_storage_interface
    session_impl o-- dht_tracker
    session_impl *-- disk_interface
    session_impl *-- resolver
    session_impl *-- i2p_connection
    session_impl *-- ip_filter
    session_impl *-- port_filter
    session_impl *-- ip_change_notifier
    session_impl "1" o-- "0..*" listen_socket_t
    session_impl *-- torrent_peer_allocator
    session_impl *-- session_settings
    session_impl *-- stat
    session_impl *-- m_utp_socket_manager

    session_impl ..|> session_interface
    session_impl ..|> dht_observer
    session_impl ..|> portmap_callback
    session_impl ..|> lsd_callback
    session_impl ..|> single_threaded
    session_impl ..|> error_handler_interface
    session_impl ..|> enable_shared_from_this

    session_impl *-- disk_interface
    session_impl *-- bandwidth_manager

    interface disk_interface

    disk_interface <|.. mmap_disk_io
    disk_interface <|.. posix_disk_io
    disk_interface <|.. disabled_disk_io

    mmap_disk_io *-- disk_job_pool

    dht_storage_interface <|.. dht_default_storage

    class torrent_list<T> {
        m_array: torrent_array
        m_index: torrent_map
    }
    torrent_list *-- torrent
    session_impl "1" o.. "0..*" torrent_list

    listen_socket_t *-- acceptor
    listen_socket_t *-- session_udp_socket

    bandwidth_manager "1" o-- "0..*" bw_request
    bw_request o-- bandwidth_socket

    interface bandwidth_socket {}
    interface disk_observer  {}
    interface peer_connection_interface {}

    peer_class_set <|-- peer_connection
    peer_connection_hot_members <|-- peer_connection
    bandwidth_socket <|.. peer_connection
    disk_observer <|.. peer_connection
    peer_connection_interface <|.. peer_connection

    single_threaded <|-- torrent
    torrent_hot_members <|-- torrent
    request_callback <|-- torrent
    peer_class_set <|-- torrent

    peer_class_pool "1" o-- "0..*" peer_class

    alert_manager "1" *-- "0..*" alert
    alert_manager o-- stack_allocator
    alert_manager o-- plugin

    plugin <|-- session_plugin_wrapper

    interface torrent_plugin {}

    torrent_plugin <|.. ut_pex_plugin
    torrent_plugin <|.. ut_metadata_plugin
    torrent_plugin <|.. smart_ban_plugin

    session_plugin_wrapper ..> torrent_plugin : create

    session_settings *-- session_settings_single_thread

    session_settings_single_thread "1" *-- "0..*" settings_pack
@enduml